// Curated monster database with 30 unique monsters
// This will be used to create a quality monster database

const MONSTER_CATALOG = [
  // ========== FIRE ELEMENT ==========
  {
    id: 'fire_001',
    name: 'Ember Sprite',
    description: 'A tiny, flickering spirit of flame that dances through the air.',
    lore: 'Born from the first spark of a campfire, Ember Sprites are curious creatures that seek out warmth and light.',
    element: 'Fire',
    type: 'Elemental',
    rarity: 'Common',
    baseHp: 45,
    baseAttack: 18,
    baseDefense: 12,
    baseSpeed: 22,
    critRate: 0.08,
    critDamage: 1.5,
    region: 'Starter Village',
    favoriteFood: 'Spicy Pepper',
    skills: [
      { name: 'Fire Spark', level: 1, damage: 15 },
      { name: 'Ember Shield', level: 1, damage: 0 }
    ],
    evolution: 'fire_002',
    evolutionStage: 1
  },
  {
    id: 'fire_002',
    name: 'Flame Wisp',
    description: 'A larger fire spirit with a core of burning coal.',
    lore: 'Flame Wisps are the evolved form of Ember Sprites, their inner coal burning with intense heat.',
    element: 'Fire',
    type: 'Elemental',
    rarity: 'Uncommon',
    baseHp: 70,
    baseAttack: 28,
    baseDefense: 18,
    baseSpeed: 28,
    critRate: 0.10,
    critDamage: 1.6,
    region: 'Burning Plains',
    favoriteFood: 'Fire Herb',
    skills: [
      { name: 'Fire Blast', level: 2, damage: 25 },
      { name: 'Heat Wave', level: 1, damage: 20 },
      { name: 'Ember Shield', level: 2, damage: 0 }
    ],
    evolution: 'fire_003',
    evolutionStage: 2
  },
  {
    id: 'fire_003',
    name: 'Inferno Drake',
    description: 'A majestic dragon wreathed in eternal flames.',
    lore: 'The Inferno Drake is a legendary creature said to have been born from a volcano\'s heart.',
    element: 'Fire',
    type: 'Dragon',
    rarity: 'Rare',
    baseHp: 120,
    baseAttack: 45,
    baseDefense: 35,
    baseSpeed: 40,
    critRate: 0.12,
    critDamage: 1.8,
    region: 'Volcanic Peak',
    favoriteFood: 'Dragon Pepper',
    skills: [
      { name: 'Inferno Breath', level: 3, damage: 50 },
      { name: 'Fire Storm', level: 2, damage: 40 },
      { name: 'Flame Shield', level: 2, damage: 0 },
      { name: 'Melt Armor', level: 1, damage: 15 }
    ],
    evolution: null,
    evolutionStage: 3
  },

  // ========== WATER ELEMENT ==========
  {
    id: 'water_001',
    name: 'Droplet Fairy',
    description: 'A small water spirit that glistens like morning dew.',
    lore: 'Droplet Fairies are born from pure mountain springs and bring luck to those they encounter.',
    element: 'Water',
    type: 'Spirit',
    rarity: 'Common',
    baseHp: 50,
    baseAttack: 15,
    baseDefense: 14,
    baseSpeed: 20,
    critRate: 0.07,
    critDamage: 1.4,
    region: 'Crystal Lake',
    favoriteFood: 'Seaweed Snack',
    skills: [
      { name: 'Water Splash', level: 1, damage: 12 },
      { name: 'Heal', level: 1, damage: 0 }
    ],
    evolution: 'water_002',
    evolutionStage: 1
  },
  {
    id: 'water_002',
    name: 'Wave Spirit',
    description: 'A graceful entity of flowing water and sea foam.',
    lore: 'Wave Spirits control the tides and can calm even the stormiest seas.',
    element: 'Water',
    type: 'Spirit',
    rarity: 'Uncommon',
    baseHp: 75,
    baseAttack: 25,
    baseDefense: 22,
    baseSpeed: 30,
    critRate: 0.09,
    critDamage: 1.5,
    region: 'Ocean Depths',
    favoriteFood: 'Pearl Fruit',
    skills: [
      { name: 'Water Blast', level: 2, damage: 28 },
      { name: 'Healing Rain', level: 2, damage: 0 },
      { name: 'Water Shield', level: 1, damage: 0 }
    ],
    evolution: 'water_003',
    evolutionStage: 2
  },
  {
    id: 'water_003',
    name: 'Leviathan',
    description: 'An ancient sea serpent of immense power and wisdom.',
    lore: 'Leviathans are the rulers of the deep oceans, appearing only during great storms.',
    element: 'Water',
    type: 'Aquatic',
    rarity: 'Epic',
    baseHp: 150,
    baseAttack: 55,
    baseDefense: 50,
    baseSpeed: 45,
    critRate: 0.11,
    critDamage: 1.7,
    region: 'Abyssal Trench',
    favoriteFood: 'Golden Kelp',
    skills: [
      { name: 'Tsunami', level: 3, damage: 60 },
      { name: 'Healing Waters', level: 3, damage: 0 },
      { name: 'Tidal Wave', level: 2, damage: 45 },
      { name: 'Oceanic Shield', level: 2, damage: 0 }
    ],
    evolution: null,
    evolutionStage: 3
  },

  // ========== EARTH ELEMENT ==========
  {
    id: 'earth_001',
    name: 'Pebble Golem',
    description: 'A small construct made of river stones and pebbles.',
    lore: 'Pebble Golems are created when a child\'s stone tower magically comes to life.',
    element: 'Earth',
    type: 'Golem',
    rarity: 'Common',
    baseHp: 60,
    baseAttack: 14,
    baseDefense: 20,
    baseSpeed: 12,
    critRate: 0.05,
    critDamage: 1.3,
    region: 'Rocky Hills',
    favoriteFood: 'Mineral Dust',
    skills: [
      { name: 'Rock Throw', level: 1, damage: 14 },
      { name: 'Stone Skin', level: 1, damage: 0 }
    ],
    evolution: 'earth_002',
    evolutionStage: 1
  },
  {
    id: 'earth_002',
    name: 'Boulder Guardian',
    description: 'A massive stone creature that protects ancient ruins.',
    lore: 'Boulder Guardians have stood watch over forgotten temples for thousands of years.',
    element: 'Earth',
    type: 'Golem',
    rarity: 'Rare',
    baseHp: 130,
    baseAttack: 35,
    baseDefense: 55,
    baseSpeed: 18,
    critRate: 0.08,
    critDamage: 1.6,
    region: 'Ancient Ruins',
    favoriteFood: 'Crystal Shards',
    skills: [
      { name: 'Earthquake', level: 2, damage: 40 },
      { name: 'Stone Shield', level: 2, damage: 0 },
      { name: 'Rock Barrage', level: 1, damage: 25 }
    ],
    evolution: null,
    evolutionStage: 2
  },

  // ========== ELECTRIC ELEMENT ==========
  {
    id: 'electric_001',
    name: 'Spark Bug',
    description: 'A tiny insect that crackles with static electricity.',
    lore: 'Spark Bugs are often found near electrical storms, feeding on lightning.',
    element: 'Electric',
    type: 'Beast',
    rarity: 'Common',
    baseHp: 40,
    baseAttack: 20,
    baseDefense: 10,
    baseSpeed: 30,
    critRate: 0.10,
    critDamage: 1.5,
    region: 'Thunder Plains',
    favoriteFood: 'Electric Berries',
    skills: [
      { name: 'Static Shock', level: 1, damage: 16 },
      { name: 'Quick Attack', level: 1, damage: 12 }
    ],
    evolution: 'electric_002',
    evolutionStage: 1
  },
  {
    id: 'electric_002',
    name: 'Thunder Hawk',
    description: 'A majestic bird that rides lightning bolts through storms.',
    lore: 'Thunder Hawks are revered as messengers of the storm gods.',
    element: 'Electric',
    type: 'Beast',
    rarity: 'Epic',
    baseHp: 100,
    baseAttack: 50,
    baseDefense: 30,
    baseSpeed: 60,
    critRate: 0.15,
    critDamage: 2.0,
    region: 'Storm Peaks',
    favoriteFood: 'Lightning Fruit',
    skills: [
      { name: 'Thunder Strike', level: 3, damage: 55 },
      { name: 'Lightning Dash', level: 2, damage: 35 },
      { name: 'Storm Call', level: 2, damage: 45 },
      { name: 'Electric Shield', level: 1, damage: 0 }
    ],
    evolution: null,
    evolutionStage: 2
  },

  // ========== WIND ELEMENT ==========
  {
    id: 'wind_001',
    name: 'Breeze Fairy',
    description: 'A playful spirit that rides on gentle winds.',
    lore: 'Breeze Fairies are the harbingers of spring, bringing new life wherever they go.',
    element: 'Wind',
    type: 'Spirit',
    rarity: 'Common',
    baseHp: 42,
    baseAttack: 16,
    baseDefense: 11,
    baseSpeed: 28,
    critRate: 0.09,
    critDamage: 1.4,
    region: 'Meadow Fields',
    favoriteFood: 'Dandelion Fluff',
    skills: [
      { name: 'Gust', level: 1, damage: 13 },
      { name: 'Wind Shield', level: 1, damage: 0 }
    ],
    evolution: 'wind_002',
    evolutionStage: 1
  },
  {
    id: 'wind_002',
    name: 'Storm Eagle',
    description: 'A powerful bird of prey that commands the winds.',
    lore: 'Storm Eagles can create tornadoes with a single flap of their wings.',
    element: 'Wind',
    type: 'Beast',
    rarity: 'Rare',
    baseHp: 95,
    baseAttack: 42,
    baseDefense: 28,
    baseSpeed: 55,
    critRate: 0.12,
    critDamage: 1.7,
    region: 'Sky Peaks',
    favoriteFood: 'Cloud Cotton',
    skills: [
      { name: 'Wind Slash', level: 2, damage: 35 },
      { name: 'Tornado', level: 2, damage: 45 },
      { name: 'Gale Force', level: 1, damage: 30 }
    ],
    evolution: null,
    evolutionStage: 2
  },

  // ========== ICE ELEMENT ==========
  {
    id: 'ice_001',
    name: 'Snowflake Spirit',
    description: 'A delicate spirit formed from the first snow of winter.',
    lore: 'Snowflake Spirits are unique - no two are exactly alike, each with their own crystalline pattern.',
    element: 'Ice',
    type: 'Spirit',
    rarity: 'Uncommon',
    baseHp: 55,
    baseAttack: 22,
    baseDefense: 16,
    baseSpeed: 24,
    critRate: 0.09,
    critDamage: 1.5,
    region: 'Frozen Tundra',
    favoriteFood: 'Ice Crystal',
    skills: [
      { name: 'Ice Shard', level: 1, damage: 18 },
      { name: 'Frost Breath', level: 1, damage: 15 }
    ],
    evolution: 'ice_002',
    evolutionStage: 1
  },
  {
    id: 'ice_002',
    name: 'Frost Wyrm',
    description: 'A serpentine dragon made of living ice and snow.',
    lore: 'Frost Wyrms are ancient beings that sleep in glaciers for centuries.',
    element: 'Ice',
    type: 'Dragon',
    rarity: 'Epic',
    baseHp: 140,
    baseAttack: 52,
    baseDefense: 45,
    baseSpeed: 38,
    critRate: 0.11,
    critDamage: 1.8,
    region: 'Glacier Peak',
    favoriteFood: 'Frozen Berry',
    skills: [
      { name: 'Blizzard', level: 3, damage: 55 },
      { name: 'Ice Breath', level: 2, damage: 40 },
      { name: 'Freeze', level: 2, damage: 30 },
      { name: 'Ice Armor', level: 1, damage: 0 }
    ],
    evolution: null,
    evolutionStage: 2
  },

  // ========== DARK ELEMENT ==========
  {
    id: 'dark_001',
    name: 'Shadow Imp',
    description: 'A mischievous creature born from darkness and shadows.',
    lore: 'Shadow Imps love to play pranks but have hearts of gold beneath their dark exterior.',
    element: 'Dark',
    type: 'Demon',
    rarity: 'Common',
    baseHp: 48,
    baseAttack: 19,
    baseDefense: 13,
    baseSpeed: 26,
    critRate: 0.10,
    critDamage: 1.6,
    region: 'Shadow Realm',
    favoriteFood: 'Dark Chocolate',
    skills: [
      { name: 'Shadow Punch', level: 1, damage: 16 },
      { name: 'Dark Veil', level: 1, damage: 0 }
    ],
    evolution: 'dark_002',
    evolutionStage: 1
  },
  {
    id: 'dark_002',
    name: 'Nightmare Stalker',
    description: 'A fearsome predator that hunts in the darkness.',
    lore: 'Nightmare Stalkers feed on fear itself, growing stronger with each victim they frighten.',
    element: 'Dark',
    type: 'Demon',
    rarity: 'Legendary',
    baseHp: 160,
    baseAttack: 65,
    baseDefense: 40,
    baseSpeed: 50,
    critRate: 0.15,
    critDamage: 2.2,
    region: 'Nightmare Dimension',
    favoriteFood: 'Fear Essence',
    skills: [
      { name: 'Dark Pulse', level: 3, damage: 65 },
      { name: 'Nightmare', level: 2, damage: 50 },
      { name: 'Shadow Step', level: 2, damage: 40 },
      { name: 'Life Drain', level: 1, damage: 30 }
    ],
    evolution: null,
    evolutionStage: 2
  },

  // ========== LIGHT ELEMENT ==========
  {
    id: 'light_001',
    name: 'Sparkle Pixie',
    description: 'A tiny creature that glows with pure holy light.',
    lore: 'Sparkle Pixies are guardians of innocence and bring hope to those in despair.',
    element: 'Light',
    type: 'Angel',
    rarity: 'Uncommon',
    baseHp: 52,
    baseAttack: 20,
    baseDefense: 18,
    baseSpeed: 25,
    critRate: 0.08,
    critDamage: 1.5,
    region: 'Holy Sanctuary',
    favoriteFood: 'Sunbeam Fruit',
    skills: [
      { name: 'Holy Light', level: 1, damage: 17 },
      { name: 'Heal', level: 1, damage: 0 }
    ],
    evolution: 'light_002',
    evolutionStage: 1
  },
  {
    id: 'light_002',
    name: 'Celestial Seraph',
    description: 'A radiant angel with wings of pure light.',
    lore: 'Celestial Seraphs are divine messengers who appear during times of great need.',
    element: 'Light',
    type: 'Angel',
    rarity: 'Mythic',
    baseHp: 180,
    baseAttack: 70,
    baseDefense: 60,
    baseSpeed: 55,
    critRate: 0.14,
    critDamage: 2.0,
    region: 'Heavenly Spire',
    favoriteFood: 'Divine Nectar',
    skills: [
      { name: 'Divine Judgment', level: 3, damage: 75 },
      { name: 'Holy Blessing', level: 3, damage: 0 },
      { name: 'Light Barrier', level: 2, damage: 0 },
      { name: 'Purify', level: 1, damage: 40 }
    ],
    evolution: null,
    evolutionStage: 2
  },

  // ========== POISON ELEMENT ==========
  {
    id: 'poison_001',
    name: 'Toxic Slime',
    description: 'A gelatinous blob of poisonous ooze.',
    lore: 'Toxic Slimes are born from contaminated swamps and leave trails of venom wherever they go.',
    element: 'Poison',
    type: 'Slime',
    rarity: 'Common',
    baseHp: 55,
    baseAttack: 17,
    baseDefense: 15,
    baseSpeed: 15,
    critRate: 0.06,
    critDamage: 1.4,
    region: 'Toxic Swamp',
    favoriteFood: 'Rotting Mushroom',
    skills: [
      { name: 'Poison Touch', level: 1, damage: 14 },
      { name: 'Acid Spray', level: 1, damage: 12 }
    ],
    evolution: 'poison_002',
    evolutionStage: 1
  },
  {
    id: 'poison_002',
    name: 'Venom Hydra',
    description: 'A multi-headed serpent dripping with deadly venom.',
    lore: 'Venom Hydras are feared throughout the land - their bite has no known cure.',
    element: 'Poison',
    type: 'Dragon',
    rarity: 'Epic',
    baseHp: 145,
    baseAttack: 58,
    baseDefense: 42,
    baseSpeed: 35,
    critRate: 0.12,
    critDamage: 1.9,
    region: 'Death Bog',
    favoriteFood: 'Toxic Root',
    skills: [
      { name: 'Venom Breath', level: 3, damage: 58 },
      { name: 'Poison Cloud', level: 2, damage: 42 },
      { name: 'Acid Rain', level: 2, damage: 38 },
      { name: 'Regenerate', level: 1, damage: 0 }
    ],
    evolution: null,
    evolutionStage: 2
  },

  // ========== PSYCHIC ELEMENT ==========
  {
    id: 'psychic_001',
    name: 'Mind Moth',
    description: 'A mystical insect that radiates psychic energy.',
    lore: 'Mind Moths are drawn to strong emotions and can sense thoughts from miles away.',
    element: 'Psychic',
    type: 'Beast',
    rarity: 'Rare',
    baseHp: 65,
    baseAttack: 30,
    baseDefense: 20,
    baseSpeed: 35,
    critRate: 0.11,
    critDamage: 1.7,
    region: 'Psychic Temple',
    favoriteFood: 'Dream Berry',
    skills: [
      { name: 'Psychic Wave', level: 2, damage: 30 },
      { name: 'Mind Read', level: 1, damage: 20 },
      { name: 'Confuse', level: 1, damage: 15 }
    ],
    evolution: 'psychic_002',
    evolutionStage: 1
  },
  {
    id: 'psychic_002',
    name: 'Astral Dragon',
    description: 'A transcendent being that exists between dimensions.',
    lore: 'Astral Dragons are said to possess infinite wisdom and can see into the future.',
    element: 'Psychic',
    type: 'Dragon',
    rarity: 'Mythic',
    baseHp: 200,
    baseAttack: 75,
    baseDefense: 65,
    baseSpeed: 60,
    critRate: 0.16,
    critDamage: 2.3,
    region: 'Astral Plane',
    favoriteFood: 'Star Essence',
    skills: [
      { name: 'Psychic Storm', level: 3, damage: 80 },
      { name: 'Reality Warp', level: 3, damage: 70 },
      { name: 'Teleport', level: 2, damage: 0 },
      { name: 'Mind Control', level: 2, damage: 50 }
    ],
    evolution: null,
    evolutionStage: 2
  },

  // ========== ADDITIONAL MONSTERS ==========
  {
    id: 'beast_001',
    name: 'Forest Wolf',
    description: 'A fierce wolf that roams the ancient forests.',
    lore: 'Forest Wolves hunt in packs and are known for their loyalty to their alpha.',
    element: 'Wind',
    type: 'Beast',
    rarity: 'Common',
    baseHp: 58,
    baseAttack: 21,
    baseDefense: 15,
    baseSpeed: 32,
    critRate: 0.09,
    critDamage: 1.5,
    region: 'Whispering Woods',
    favoriteFood: 'Wild Meat',
    skills: [
      { name: 'Bite', level: 1, damage: 16 },
      { name: 'Howl', level: 1, damage: 10 }
    ],
    evolution: null,
    evolutionStage: 1
  },
  {
    id: 'undead_001',
    name: 'Skeleton Knight',
    description: 'An armored skeleton that rises to protect ancient graves.',
    lore: 'Skeleton Knights were once noble warriors, bound to protect their tombs for eternity.',
    element: 'Dark',
    type: 'Undead',
    rarity: 'Uncommon',
    baseHp: 80,
    baseAttack: 26,
    baseDefense: 30,
    baseSpeed: 20,
    critRate: 0.08,
    critDamage: 1.5,
    region: 'Cursed Catacombs',
    favoriteFood: 'Bone Dust',
    skills: [
      { name: 'Bone Slash', level: 1, damage: 22 },
      { name: 'Shield Bash', level: 1, damage: 18 },
      { name: 'Undead Resilience', level: 1, damage: 0 }
    ],
    evolution: null,
    evolutionStage: 1
  },
  {
    id: 'plant_001',
    name: 'Vine Whip',
    description: 'A sentient plant that attacks with thorny vines.',
    lore: 'Vine Whips protect ancient forests and can sense intruders from miles away.',
    element: 'Earth',
    type: 'Plant',
    rarity: 'Common',
    baseHp: 52,
    baseAttack: 18,
    baseDefense: 16,
    baseSpeed: 18,
    critRate: 0.07,
    critDamage: 1.4,
    region: 'Enchanted Forest',
    favoriteFood: 'Sunlight',
    skills: [
      { name: 'Vine Whip', level: 1, damage: 15 },
      { name: 'Photosynthesis', level: 1, damage: 0 }
    ],
    evolution: null,
    evolutionStage: 1
  },
  {
    id: 'machine_001',
    name: 'Clockwork Beetle',
    description: 'A mechanical insect powered by tiny gears and springs.',
    lore: 'Clockwork Beetles were created by ancient engineers and still function after millennia.',
    element: 'Electric',
    type: 'Machine',
    rarity: 'Rare',
    baseHp: 85,
    baseAttack: 32,
    baseDefense: 38,
    baseSpeed: 28,
    critRate: 0.10,
    critDamage: 1.6,
    region: 'Ancient Workshop',
    favoriteFood: 'Oil Drops',
    skills: [
      { name: 'Gear Slash', level: 2, damage: 28 },
      { name: 'Shock', level: 2, damage: 25 },
      { name: 'Repair', level: 1, damage: 0 }
    ],
    evolution: null,
    evolutionStage: 1
  },
  {
    id: 'dragon_001',
    name: 'Dragon Whelp',
    description: 'A young dragon still learning to control its powers.',
    lore: 'Dragon Whelps are playful and curious, often causing accidental destruction.',
    element: 'Fire',
    type: 'Dragon',
    rarity: 'Uncommon',
    baseHp: 75,
    baseAttack: 28,
    baseDefense: 22,
    baseSpeed: 25,
    critRate: 0.10,
    critDamage: 1.6,
    region: 'Dragon Valley',
    favoriteFood: 'Cooked Meat',
    skills: [
      { name: 'Fire Breath', level: 1, damage: 22 },
      { name: 'Tail Whip', level: 1, damage: 15 }
    ],
    evolution: 'dragon_002',
    evolutionStage: 1
  },
  {
    id: 'dragon_002',
    name: 'Adult Dragon',
    description: 'A fully grown dragon in the prime of its power.',
    lore: 'Adult Dragons are formidable warriors capable of destroying entire armies.',
    element: 'Fire',
    type: 'Dragon',
    rarity: 'Epic',
    baseHp: 160,
    baseAttack: 60,
    baseDefense: 50,
    baseSpeed: 45,
    critRate: 0.13,
    critDamage: 1.9,
    region: 'Dragon Peak',
    favoriteFood: 'Whole Sheep',
    skills: [
      { name: 'Dragon Breath', level: 3, damage: 60 },
      { name: 'Wing Attack', level: 2, damage: 40 },
      { name: 'Fire Shield', level: 2, damage: 0 },
      { name: 'Roar', level: 1, damage: 25 }
    ],
    evolution: 'dragon_003',
    evolutionStage: 2
  },
  {
    id: 'dragon_003',
    name: 'Ancient Dragon',
    description: 'An ancient dragon with wisdom spanning millennia.',
    lore: 'Ancient Dragons are the oldest and most powerful of their kind, possessing immense knowledge.',
    element: 'Fire',
    type: 'Dragon',
    rarity: 'Legendary',
    baseHp: 250,
    baseAttack: 85,
    baseDefense: 75,
    baseSpeed: 55,
    critRate: 0.15,
    critDamage: 2.2,
    region: 'Dragon Sanctum',
    favoriteFood: 'Phoenix Egg',
    skills: [
      { name: 'Ancient Breath', level: 3, damage: 85 },
      { name: 'Dragon Rage', level: 3, damage: 70 },
      { name: 'Time Warp', level: 2, damage: 60 },
      { name: 'Immortal Shield', level: 2, damage: 0 }
    ],
    evolution: null,
    evolutionStage: 3
  },
  {
    id: 'goblin_001',
    name: 'Goblin Scout',
    description: 'A sneaky goblin that excels at stealth and thievery.',
    lore: 'Goblin Scouts are the eyes and ears of goblin tribes, always looking for easy prey.',
    element: 'Dark',
    type: 'Beast',
    rarity: 'Common',
    baseHp: 45,
    baseAttack: 19,
    baseDefense: 11,
    baseSpeed: 30,
    critRate: 0.10,
    critDamage: 1.5,
    region: 'Goblin Camp',
    favoriteFood: 'Stolen Bread',
    skills: [
      { name: 'Steal', level: 1, damage: 14 },
      { name: 'Quick Slash', level: 1, damage: 16 }
    ],
    evolution: null,
    evolutionStage: 1
  },
  {
    id: 'orc_001',
    name: 'Orc Warrior',
    description: 'A strong orc fighter wielding a massive axe.',
    lore: 'Orc Warriors live for battle and respect only strength above all else.',
    element: 'Earth',
    type: 'Beast',
    rarity: 'Uncommon',
    baseHp: 90,
    baseAttack: 30,
    baseDefense: 25,
    baseSpeed: 18,
    critRate: 0.08,
    critDamage: 1.6,
    region: 'Orc Fortress',
    favoriteFood: 'Roast Boar',
    skills: [
      { name: 'Axe Swing', level: 1, damage: 25 },
      { name: 'War Cry', level: 1, damage: 15 }
    ],
    evolution: null,
    evolutionStage: 1
  },
  {
    id: 'slime_001',
    name: 'Gelatinous Slime',
    description: 'A bouncy blob of jelly that absorbs everything it touches.',
    lore: 'Slimes are mysterious creatures that can take any shape and survive almost anything.',
    element: 'Water',
    type: 'Slime',
    rarity: 'Common',
    baseHp: 60,
    baseAttack: 12,
    baseDefense: 18,
    baseSpeed: 10,
    critRate: 0.05,
    critDamage: 1.3,
    region: 'Slime Plains',
    favoriteFood: 'Everything',
    skills: [
      { name: 'Body Slam', level: 1, damage: 13 },
      { name: 'Absorb', level: 1, damage: 0 }
    ],
    evolution: null,
    evolutionStage: 1
  },
  {
    id: 'troll_001',
    name: 'Cave Troll',
    description: 'A brutish troll that lives in dark caves and bridges.',
    lore: 'Cave Trolls are known for their incredible strength and regenerative abilities.',
    element: 'Earth',
    type: 'Beast',
    rarity: 'Rare',
    baseHp: 140,
    baseAttack: 40,
    baseDefense: 30,
    baseSpeed: 15,
    critRate: 0.07,
    critDamage: 1.5,
    region: 'Dark Caves',
    favoriteFood: 'Rocks and Minerals',
    skills: [
      { name: 'Club Smash', level: 2, damage: 38 },
      { name: 'Regenerate', level: 2, damage: 0 },
      { name: 'Boulder Throw', level: 1, damage: 30 }
    ],
    evolution: null,
    evolutionStage: 1
  },
  {
    id: 'phantom_001',
    name: 'Wraith',
    description: 'A spectral entity that drifts through walls and barriers.',
    lore: 'Wraiths are souls trapped between worlds, seeking peace that never comes.',
    element: 'Dark',
    type: 'Undead',
    rarity: 'Rare',
    baseHp: 95,
    baseAttack: 38,
    baseDefense: 25,
    baseSpeed: 45,
    critRate: 0.12,
    critDamage: 1.8,
    region: 'Haunted Manor',
    favoriteFood: 'Soul Fragments',
    skills: [
      { name: 'Spectral Strike', level: 2, damage: 35 },
      { name: 'Phase Shift', level: 2, damage: 0 },
      { name: 'Soul Drain', level: 1, damage: 25 }
    ],
    evolution: null,
    evolutionStage: 1
  },
  {
    id: 'holy_001',
    name: 'Unicorn Foal',
    description: 'A young unicorn with a shimmering horn of light.',
    lore: 'Unicorn Foals are pure of heart and can heal any wound with their magical horns.',
    element: 'Light',
    type: 'Beast',
    rarity: 'Epic',
    baseHp: 110,
    baseAttack: 35,
    baseDefense: 40,
    baseSpeed: 40,
    critRate: 0.10,
    critDamage: 1.7,
    region: 'Enchanted Glade',
    favoriteFood: 'Moonflower',
    skills: [
      { name: 'Horn Strike', level: 2, damage: 32 },
      { name: 'Purify', level: 2, damage: 0 },
      { name: 'Heal', level: 2, damage: 0 }
    ],
    evolution: null,
    evolutionStage: 1
  },
  {
    id: 'titan_001',
    name: 'Stone Titan',
    description: 'A colossal giant made of living rock and granite.',
    lore: 'Stone Titans were created by the gods to hold up the mountains themselves.',
    element: 'Earth',
    type: 'Golem',
    rarity: 'Legendary',
    baseHp: 300,
    baseAttack: 70,
    baseDefense: 90,
    baseSpeed: 20,
    critRate: 0.08,
    critDamage: 1.6,
    region: 'Mountain Core',
    favoriteFood: 'Mountain Ore',
    skills: [
      { name: 'Titan Smash', level: 3, damage: 75 },
      { name: 'Earthquake', level: 3, damage: 65 },
      { name: 'Stone Skin', level: 3, damage: 0 },
      { name: 'Boulder Throw', level: 2, damage: 50 }
    ],
    evolution: null,
    evolutionStage: 1
  }
];

module.exports = { MONSTER_CATALOG };